# 💰 Funding Configuration for Shai-Hulud Detector
# https://docs.github.com/en/github/administering-a/usage-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository

# GitHub sponsors - Uncomment when enrolled in GitHub Sponsors program
# github: josedacosta

# Other funding platforms
custom: [ "https://www.buymeacoffee.com/josedacosta", "https://ko-fi.com/josedacosta" ]
